productos = {
    "Arroz": {"Cantidad": "20 kg", "Precio": "$30"},
    "Frijoles": {"Cantidad": "15 kg", "Precio": "$25"},
    "Azúcar": {"Cantidad": "10 kg", "Precio": "$20"},
    "Harina": {"Cantidad": "12 kg", "Precio": "$18"},
    "Pan": {"Cantidad": "50 piezas", "Precio": "$2"},
    "Pasta": {"Cantidad": "25 paquetes", "Precio": "$10"},
    "Aceite": {"Cantidad": "30 botellas", "Precio": "$15"},
    "Sal": {"Cantidad": "10 kg", "Precio": "$5"},
    "Café": {"Cantidad": "5 paquetes", "Precio": "$12"},
    "Galletas": {"Cantidad": "100 paquetes", "Precio": "$3"},
    "Cereales": {"Cantidad": "10 cajas", "Precio": "$25"},
    "Salsa": {"Cantidad": "15 botellas", "Precio": "$7"},
    "Salsa de soya": {"Cantidad": "20 botellas", "Precio": "$10"},
    "Leche": {"Cantidad": "30 litros", "Precio": "$12"},
    "Jugos": {"Cantidad": "40 botellas", "Precio": "$8"},
    "Té": {"Cantidad": "25 cajas", "Precio": "$6"},
    "Sopas instantáneas": {"Cantidad": "60 paquetes", "Precio": "$4"},
    "Mayonesa": {"Cantidad": "15 frascos", "Precio": "$18"},
    "Mostaza": {"Cantidad": "10 frascos", "Precio": "$7"},
    "Vinagre": {"Cantidad": "10 botellas", "Precio": "$5"},
    "Mermelada": {"Cantidad": "12 frascos", "Precio": "$9"},
    "Atún enlatado": {"Cantidad": "30 latas", "Precio": "$12"},
    "Sardinas": {"Cantidad": "20 latas", "Precio": "$9"},
    "Jamón": {"Cantidad": "10 kg", "Precio": "$80"},
    "Queso": {"Cantidad": "8 kg", "Precio": "$60"},
    "Yogurt": {"Cantidad": "25 unidades", "Precio": "$2"},
    "Huevos": {"Cantidad": "10 docenas", "Precio": "$40"},
    "Tortillas": {"Cantidad": "100 paquetes", "Precio": "$15"},
    "Pasta de dientes": {"Cantidad": "40 tubos", "Precio": "$6"},
    "Papel higiénico": {"Cantidad": "50 rollos", "Precio": "$20"},
    "Servilletas": {"Cantidad": "30 paquetes", "Precio": "$5"},
    "Detergente": {"Cantidad": "25 botellas", "Precio": "$10"},
    "Cloro": {"Cantidad": "15 botellas", "Precio": "$6"},
    "Jabón": {"Cantidad": "40 barras", "Precio": "$3"},
    "Desinfectante": {"Cantidad": "10 botellas", "Precio": "$8"},
    "Limpiadores multiusos": {"Cantidad": "20 botellas", "Precio": "$7"},
    "Suavizantes": {"Cantidad": "15 botellas", "Precio": "$9"},
    "Velas": {"Cantidad": "30 paquetes", "Precio": "$2"},
    "Fósforos": {"Cantidad": "50 cajas", "Precio": "$1"},
    "Baterías": {"Cantidad": "20 paquetes", "Precio": "$10"},
    "Latas de vegetales": {"Cantidad": "25 latas", "Precio": "$5"},
    "Frutas en conserva": {"Cantidad": "20 latas", "Precio": "$7"},
    "Comino": {"Cantidad": "10 frascos", "Precio": "$3"},
    "Pimienta": {"Cantidad": "10 frascos", "Precio": "$4"},
    "Caldo de pollo": {"Cantidad": "30 cubos", "Precio": "$2"},
    "Chocolate en polvo": {"Cantidad": "15 bolsas", "Precio": "$10"},
    "Pan dulce": {"Cantidad": "60 piezas", "Precio": "$1.50"},
    "Pan de caja": {"Cantidad": "40 piezas", "Precio": "$10"},
    "Papas fritas": {"Cantidad": "30 bolsas", "Precio": "$5"},
    "Cacahuates": {"Cantidad": "20 bolsas", "Precio": "$4"},
    "Galletas saladas": {"Cantidad": "25 paquetes", "Precio": "$3"},
    "Sopa de pollo": {"Cantidad": "15 latas", "Precio": "$8"},
    "Frijoles refritos": {"Cantidad": "10 latas", "Precio": "$6"},
    "Mantequilla": {"Cantidad": "5 kg", "Precio": "$35"},
    "Leche condensada": {"Cantidad": "10 latas", "Precio": "$12"},
    "Acelga enlatada": {"Cantidad": "15 latas", "Precio": "$5"},
    "Sopa de fideos": {"Cantidad": "25 paquetes", "Precio": "$4"},
    "Aceitunas": {"Cantidad": "20 frascos", "Precio": "$9"},
    "Tetra Pak de leche": {"Cantidad": "30 unidades", "Precio": "$11"},
    "Refresco": {"Cantidad": "50 botellas", "Precio": "$10"},
    "Chicles": {"Cantidad": "100 paquetes", "Precio": "$1"},
    "Cereal de desayuno": {"Cantidad": "20 cajas", "Precio": "$15"},
    "Galletas de chocolate": {"Cantidad": "30 paquetes", "Precio": "$5"},
    "Harina de maíz": {"Cantidad": "15 kg", "Precio": "$12"},
    "Cereal de maíz": {"Cantidad": "10 cajas", "Precio": "$10"},
    "Té verde": {"Cantidad": "10 cajas", "Precio": "$9"},
    "Arroz integral": {"Cantidad": "5 kg", "Precio": "$40"}
}
